In [1]:
# I start by uploading and rading the weather data
import pandas as pd

weather = pd.read_csv('Rogers hourly weather data.csv')

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
print(weather)
#weather.head()
print(weather.columns)

                                location_id              datetime_beginning  \
0      819ad24f-585c-4050-8b51-9d682a7a7243  2022-01-01 00:00:00.000000 UTC
1      819ad24f-585c-4050-8b51-9d682a7a7243  2022-01-01 01:00:00.000000 UTC
2      819ad24f-585c-4050-8b51-9d682a7a7243  2022-01-01 02:00:00.000000 UTC
3      819ad24f-585c-4050-8b51-9d682a7a7243  2022-01-01 03:00:00.000000 UTC
4      819ad24f-585c-4050-8b51-9d682a7a7243  2022-01-01 04:00:00.000000 UTC
...                                     ...                             ...
17490  819ad24f-585c-4050-8b51-9d682a7a7243  2023-12-30 20:00:00.000000 UTC
17491  819ad24f-585c-4050-8b51-9d682a7a7243  2023-12-30 21:00:00.000000 UTC
17492  819ad24f-585c-4050-8b51-9d682a7a7243  2023-12-30 22:00:00.000000 UTC
17493  819ad24f-585c-4050-8b51-9d682a7a7243  2023-12-30 23:00:00.000000 UTC
17494  819ad24f-585c-4050-8b51-9d682a7a7243  2023-12-31 00:00:00.000000 UTC

       temp_f  dewpoint_f  humidity  windspeed_mph  pressure_millibars  \
0       58.75       54.39        85          14.13              1005.2
1       57.42       54.17        89          13.78              1005.2
2       57.07       54.19        90          13.24              1007.0
3       57.08       55.24        94           7.93              1007.0
4       57.40       55.19        92           4.89              1006.1
...       ...         ...       ...            ...                 ...
17490   52.10       37.16        57           3.06              1021.8
17491   51.33       36.90        58           3.01              1020.8
17492   51.39       37.67        59           3.01              1020.8
17493   50.55       38.31        63           1.68              1020.8
17494   47.97       36.85        65           1.86              1021.8

       cloud_percentage  precip_rate_mm_per_hour weather_conditions  \
0                   100                     0.25       Rain Showers
1                   100                     0.55       Rain Showers
2                   100                     1.06   Isolated Showers
3                   100                     0.40       Rain Showers
4                   100                     0.25       Rain Showers
...                 ...                      ...                ...
17490                 2                     0.00              Sunny
17491                 0                     0.00              Sunny
17492                 2                     0.00              Sunny
17493                 0                     0.00              Sunny
17494                 3                     0.00              Clear

       horizontal_irradiance_watts_per_m2                      created_at
0                                  0.0000  2023-11-16 13:19:09.119975 UTC
1                                  0.0000  2023-11-16 13:19:09.119975 UTC
2                                  0.0000  2023-11-16 13:19:09.119975 UTC
3                                  0.0000  2023-11-16 13:19:09.119975 UTC
4                                  0.0000  2023-11-16 13:19:09.119975 UTC
...                                   ...                             ...
17490                            423.9294  2024-01-17 21:28:14.104756 UTC
17491                            299.6500  2024-01-17 21:28:14.104756 UTC
17492                            136.8398  2024-01-17 21:28:14.104756 UTC
17493                              2.3300  2024-01-17 21:28:14.104756 UTC
17494                              0.0000  2024-01-17 21:28:14.104756 UTC

[17495 rows x 12 columns]
Index(['location_id', 'datetime_beginning', 'temp_f', 'dewpoint_f', 'humidity',
       'windspeed_mph', 'pressure_millibars', 'cloud_percentage',
       'precip_rate_mm_per_hour', 'weather_conditions',
       'horizontal_irradiance_watts_per_m2', 'created_at'],
      dtype='object')

In [3]:
# I create the base temperature for HDD and CDD. Based on the results of the regression model, I will change the values to improve
# the R^2 value. As discussed in class, it is better to set the baseload to a temperature interval rather than single value.
base_temp_hdd = 35
base_temp_cdd = 45

# I then convert the datetime values in the weather file into datetime objects, and I set it to the index

weather['datetime_beginning'] = pd.to_datetime(weather['datetime_beginning'])
weather.set_index('datetime_beginning', inplace=True)

In [4]:
# I calculate the daily average temperature from the hourly temperature values 
daily_avg_temp = weather['temp_f'].resample('D').mean()
print(daily_avg_temp)

# Then I create a zeros-list for HDD and CDD

hdd = pd.Series(0, index=daily_avg_temp.index)
cdd = pd.Series(0, index=daily_avg_temp.index)

# laslty, I calculate and assign values to HDD or CDD based on the average temperature being smaller or larger than the corresponding base temperature

for day in daily_avg_temp.index:
    avg_temp = daily_avg_temp[day]
    if avg_temp < base_temp_hdd:
        hdd[day] = base_temp_hdd - avg_temp
    elif avg_temp > base_temp_cdd:
        cdd[day] = avg_temp - base_temp_cdd
        
print(hdd)

datetime_beginning
2022-01-01 00:00:00+00:00    52.404167
2022-01-02 00:00:00+00:00    18.646667
2022-01-03 00:00:00+00:00    25.766667
2022-01-04 00:00:00+00:00    36.555833
2022-01-05 00:00:00+00:00    37.512083
                               ...
2023-12-27 00:00:00+00:00    38.065417
2023-12-28 00:00:00+00:00    34.590833
2023-12-29 00:00:00+00:00    33.813333
2023-12-30 00:00:00+00:00    35.020000
2023-12-31 00:00:00+00:00    47.970000
Freq: D, Name: temp_f, Length: 730, dtype: float64
datetime_beginning
2022-01-01 00:00:00+00:00     0.000000
2022-01-02 00:00:00+00:00    16.353333
2022-01-03 00:00:00+00:00     9.233333
2022-01-04 00:00:00+00:00     0.000000
2022-01-05 00:00:00+00:00     0.000000
                               ...
2023-12-27 00:00:00+00:00     0.000000
2023-12-28 00:00:00+00:00     0.409167
2023-12-29 00:00:00+00:00     1.186667
2023-12-30 00:00:00+00:00     0.000000
2023-12-31 00:00:00+00:00     0.000000
Freq: D, Length: 730, dtype: float64

In [5]:
#I create a dataframe to align average temperature, HDD and CDD by date
result_df = pd.DataFrame({
    'date': daily_avg_temp.index.date,
    'daily_avg_temp': daily_avg_temp.values,
    'hdd': hdd.values,
    'cdd': cdd.values
})

# I then set the date as the index
result_df.set_index('date', inplace=True)

result_df.index = pd.to_datetime(result_df.index)

result_df

            daily_avg_temp        hdd       cdd
date
2022-01-01       52.404167   0.000000  7.404167
2022-01-02       18.646667  16.353333  0.000000
2022-01-03       25.766667   9.233333  0.000000
2022-01-04       36.555833   0.000000  0.000000
2022-01-05       37.512083   0.000000  0.000000
...                    ...        ...       ...
2023-12-27       38.065417   0.000000  0.000000
2023-12-28       34.590833   0.409167  0.000000
2023-12-29       33.813333   1.186667  0.000000
2023-12-30       35.020000   0.000000  0.000000
2023-12-31       47.970000   0.000000  2.970000

[730 rows x 3 columns]

In [6]:
pip install seaborn

Requirement already satisfied: seaborn in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from seaborn) (1.25.2)
Requirement already satisfied: pandas>=1.2 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from seaborn) (2.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from seaborn) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (23.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2022.7)
Requirement already satisfied: tzdata>=2022.1 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/tommy/Downloads/yes/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
# I load the building energy data that I want to weather normalize
file_path = 'Building energy data 2022-2023.xlsx'

energy = pd.read_excel(file_path)

In [8]:
# I convert the Month column in the energy data to datetime, and I make sure its the same object type in result_df
energy['Month'] = pd.to_datetime(energy['Month'])
result_df['Month'] = result_df.index.to_period('M').to_timestamp()

# I Calculate the average monthly temperature in result_df so that I can align it with monthly energy data
monthly_avg_temp = result_df.groupby('Month')['daily_avg_temp'].mean().reset_index()

# I group result_df by Month and sum the HDD and CDD, and get the average temperature, and the I merge everything
monthly_hdd_cdd_temp = result_df.groupby('Month').agg({'hdd': 'sum', 'cdd': 'sum', 'daily_avg_temp': 'mean'}).reset_index()
combined_data = pd.merge(energy, monthly_hdd_cdd_temp, on='Month', how='left')
combined_data.rename(columns={'daily_avg_temp': 'monthly_avg_temp'}, inplace=True)

In [9]:
# I save and display the data 

excel_filename = 'combined_data.xlsx'

combined_data.to_excel(excel_filename)

combined_data

        Month  Energy_kBTU         hdd          cdd  monthly_avg_temp
0  2022-01-01    207587.81  120.232500    16.848333         35.330134
1  2022-02-01    192273.75  105.507083    60.885000         38.241949
2  2022-03-01    142413.91   15.186250   222.702083         49.658589
3  2022-04-01    144601.84    0.000000   376.551667         57.356778
4  2022-05-01    216202.18    0.000000   690.279583         67.267083
5  2022-06-01    207574.12    0.000000   965.627917         77.187597
6  2022-07-01    221767.53    0.000000  1221.828750         84.413831
7  2022-08-01    267570.39    0.000000  1035.028333         78.388011
8  2022-09-01    222621.76    0.000000   802.103750         71.736792
9  2022-10-01    170340.21    0.000000   484.587083         60.262245
10 2022-11-01    156848.45   21.626667   202.540924         47.519614
11 2022-12-01    187555.95   98.067917    80.445000         40.038360
12 2023-01-01    162782.98   47.516250    85.010417         41.611895
13 2023-02-01    167462.61   24.578333   111.010417         44.819613
14 2023-03-01    144387.55    6.538333   187.835417         49.134731
15 2023-04-01    156342.47    0.000000   408.595000         58.619833
16 2023-05-01    207458.32    0.000000   668.116667         66.552151
17 2023-06-01    186997.69    0.000000   887.152083         74.571736
18 2023-07-01    261545.09    0.000000  1060.912500         79.222984
19 2023-08-01    260308.73    0.000000  1050.817083         78.897325
20 2023-09-01    199221.69    0.000000   800.599167         71.686639
21 2023-10-01    166068.83    1.261250   482.274167         59.844866
22 2023-11-01    142825.07    0.695833   217.434149         50.801374
23 2023-12-01    156126.52    1.595833    86.960000         45.063051

In [10]:
# I notice that the enrgy (kBTU) always reaches its mininum when the monthly average temperature is around 50 ºF. 
# That suggests me that the best baseline is around that temperature. I now go back and change the base temperatures for 
# HDD and CDD, and rerun the code until here.

In [11]:
# I build a linear regression model of the monthly energy data regressed on HDD and CDD. This wil confirm if 
# the base temperatures chosen were more or less exact

import statsmodels.api as sm

# I filter the dataset for the baseline year - 2022  
baseline_data = combined_data[combined_data['Month'].dt.year == 2022]

# I define the dependent and independent variables for the baseline year
y_baseline = baseline_data['Energy_kBTU']
X_baseline = baseline_data[['hdd', 'cdd']]

# I add a constant to the independent variable set
X_baseline = sm.add_constant(X_baseline)

# I fit the regression model on the baseline year data
model_baseline = sm.OLS(y_baseline, X_baseline).fit()

print(model_baseline.summary())

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
                            OLS Regression Results
==============================================================================
Dep. Variable:            Energy_kBTU   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.700
Method:                 Least Squares   F-statistic:                     13.83
Date:                Thu, 29 Feb 2024   Prob (F-statistic):            0.00180
Time:                        16:18:53   Log-Likelihood:                -134.26
No. Observations:                  12   AIC:                             274.5
Df Residuals:                       9   BIC:                             276.0
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.171e+05   1.66e+04      7.060      0.000    7.96e+04    1.55e+05
hdd          676.2998    187.014      3.616      0.006     253.245    1099.355
cdd          111.8047     21.298      5.249      0.001      63.624     159.985
==============================================================================
Omnibus:                        0.309   Durbin-Watson:                   2.296
Prob(Omnibus):                  0.857   Jarque-Bera (JB):                0.180
Skew:                           0.235   Prob(JB):                        0.914
Kurtosis:                       2.628   Cond. No.                     1.85e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.85e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

/Users/tommy/Downloads/yes/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1971: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=12
  k, _ = kurtosistest(a, axis)

In [12]:
# After some comparison with different values for base temperatures, the highest R^2 value is for base_temp_hdd = 35
# and base_temp_cdd = 45. This shows that the best base temperatures are a little bit lower than the predicted 50 ºF